export const MAX_TAG_LENGTH_HOME_PAGE = 7;
export const MAX_TAG_LENGTH_SINGLE_PAGE = 11;
export const MAX_TAGS_PER_RECIPE = 4;
export const MAX_RECIPE_NAME_LENGTH = 23;
export const MAX_CUISINE_NAME_LENGTH = 9;
export const NUMBER_OF_RECIPES_LOADED_AT_ONCE = 6;
